#Contains compatibility options.
[compatibility]

	#Contains compatibility options for the JEI mod.
	[compatibility.compatibility]
		#Whether to show blocks for all wood types in JEI, or just the default oak.
		show_wood_types = true
		#Whether to show blocks for all color types in JEI, or just the default white.
		show_color_types = true
